### ISSUE TITLE
Inconsistencies in author names between "abstracts" file and "session_papers.tsv"

### ISSUE THREAD

**Issue by MinaAlmasi** [cohure/CHR2024-website#42]
Hi - thanks for the files and help! Just a quick note. I have added the CHR programme, auto-generating all paper titles, authors etc.  with the `abstracts.json` (from @fbkarsdorp) and `session_papers.tsv` (from @marijnkoolen). The [py file](https://github.com/cohure/website-automatisation/blob/main/src/utils.py) that processed the pages is in the new [cohure/website-automatisation](https://github.com/cohure/website-automatisation).

### Issue: Inconsistencies in Author Names Between the Two Files
I started by extracting authors from `abstracts.json`, but later on switched to `session_papers.tsv` (as it matches exactly the PDF `CHR2024_DRAFTProgram_v2.pdf`). 

When doing this switch, I noted that there were quite a few papers that had small (an added middle name) or big changes (and author extra): 
<img width="30%" alt="paper-changes" src="https://github.com/user-attachments/assets/f999b4d9-68a6-426a-8893-4332ee3a887f">

E.g., a paper by "Taylor Arnold" (paper_id = 1) has an extra author in the "abtracts.json" (that is not present in `session_papers.tsv` nor `CHR2024_DRAFTProgram_v2.pdf`). However, the abtracts.json also seems to also have some errors. 

You can see the full extent of the changes in this commit: https://github.com/cohure/CHR2024-website/commit/687137424d97c3dc6049b6c6e79a6f704dd0ccbe#diff-fe98728e252fa55d4fc78335ee25b33b1b7af051ccc68a16a26170ad3bc61b4eR42

### Steps going forward
Can you, @marijnkoolen, check that the authors in `session_papers.tsv` are correct? Otherwise you can let me know, and I'll update the website! 

### Update: 
A colleague also told me that there was something wrong with the order of their authors: https://2024.computational-humanities-research.org/papers/paper106/

This order is also how it is present in the `CHR2024_DRAFTProgram_v2.pdf`

**Comment by marijnkoolen** [comment]
Ouch, good that you caught these issues. The info in `session_papers.tsv` is based on the initial submissions I think. The info in `abstracts.json` is derived from the final PDFs and author-provided metadata, so that's more correct. In other words, please use author and title from `abstracts.json` and only use `session_papers.tsv` to extract the same names and numbers. 

The order of authors should also be based on `abstracts.json`. And we also need to generate a new PDF of the programme with these updates.

**Comment by MinaAlmasi** [comment]
But the abstracts json also had some weird things (middle names etc.) and e.g., different order of first name / last name that confused me: 
<img width="1389" alt="Screenshot 2024-11-12 at 14 49 11" src="https://github.com/user-attachments/assets/25ca11a7-bf5f-48be-91a2-7bb997266020">

**Comment by awlassche** [comment]
The different order of first and last name might be due to the habit in Asian countries that the surname is written first, then the given names.

**Comment by marijnkoolen** [comment]
Ah, yes. I think some authors filled in their names in EasyChair in the wrong order. The abstracts json contains the latest info as provided by the authors. The name of the first author that you show above for paper 141 in `abstracts.json` is the same as it is in the PDF of their paper, so I think we should assume that that is the correct version.

I'm regenerating the `session_papers.tsv` to reflect those changes.

**Comment by MinaAlmasi** [comment]
Awesome - thank you both for the quick response! If you don't mind uploading the new `session_papers.tsv` to the [cohure/website-automatisation](https://github.com/cohure/website-automatisation), @marijnkoolen, that would be awesome! 

Otherwise, I'll tinker with extracting it from `abstracts.json`

**Comment by marijnkoolen** [comment]
I've updated `session_papers.tsv` with the new paper info and added the posters as well.

**Comment by MinaAlmasi** [comment]
Thank you so much, @marijnkoolen !!

**Comment by MinaAlmasi** [comment]
Hey again - I just noticed an inconsistency in titles also - should I'll use the `abtracts.json` for this information, but just in case you were editing the pdf draft, I wanted to let you know! @marijnkoolen

**Comment by marijnkoolen** [comment]
Yes, I'm updating the spreadsheet that is the source for the PDF version of the programme with the titles and authors as listed in `abstracts.json`.

**Comment by marijnkoolen** [comment]
Many thanks @MinaAlmasi for doing all this! It's great to see the programme online. I just noticed that the PDF links mention the volume number of last year's conference (3558). I think that might confuse people, since the links leads them to a 404, but it suggests that either the volume number or the PDF name is wrong. 

I think it's better to either:
- remove the link for now and add (TBA), e.g. "Download PDF (TBA)". That way people know the link is still to come.
- replace the volume number with "TBA" or "dummy" (e.g. https://ceur-ws.org/Vol-TBA/paper74.pdf). They still get the 404, but when they check the URL, they might understand it's a temporary dummy link.

I have a preference for the first option, but if it's too much hassle, the second is also fine.

**Comment by MinaAlmasi** [comment]
> * remove the link for now and add (TBA), e.g. "Download PDF (TBA)". That way people know the link is still to come.
> * replace the volume number with "TBA" or "dummy" (e.g. https://ceur-ws.org/Vol-TBA/paper74.pdf). They still get the 404, but when they check the URL, they might understand it's a temporary dummy link.

Pushed to website in #45

**Comment by MinaAlmasi** [comment]
Closing this now - feel free to reopen if necessary!
